#!/usr/bin/env python3
"""mac/Sources/LRMacStrings.inc from mac_strings.py, and a check that every
L(@"...") of the mac sources has a russian translation in one of the tables"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).parent))
from mac_strings import STRINGS  # noqa: E402


def c_literal(s):
    # the english keys are taken as written in the objective-c source
    return s.replace('"', '\\"') if '\\"' not in s else s


def main():
    out = ["/* generated by scripts/l10n/build_mac_inc.py: edit mac_strings.py */"]
    seen = set()
    for en, ru, zh in STRINGS:
        if en in seen:
            continue
        seen.add(en)
        out.append('    { "%s", "%s", "%s" },' % (c_literal(en), c_literal(ru), c_literal(zh)))
    (ROOT / "mac" / "Sources" / "LRMacStrings.inc").write_text("\n".join(out) + "\n")
    inc = (ROOT / "app" / "Sources" / "Core" / "LRStrings.inc").read_text()
    known = set(m.group(1) for m in re.finditer(r'\{ "((?:[^"\\]|\\.)*)", "', inc)) | set(
        c_literal(e) for e in seen)
    missing = []
    for f in sorted((ROOT / "mac" / "Sources").rglob("*.m")):
        for m in re.finditer(r'L\(@"((?:[^"\\]|\\.)*)"\)', f.read_text()):
            if m.group(1) not in known and m.group(1) not in missing:
                missing.append(m.group(1))
    print(f"{len(seen)} mac strings, {len(missing)} without a translation")
    for k in missing:
        print("  ", k)


if __name__ == "__main__":
    main()
